CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `questions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `question` text NOT NULL,
  `choice_a` varchar(255) NOT NULL,
  `choice_b` varchar(255) NOT NULL,
  `choice_c` varchar(255) NOT NULL,
  `choice_d` varchar(255) NOT NULL,
  `correct_choice` char(1) NOT NULL,
  `question_id` int DEFAULT NULL,
  `Test_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Test_id` (`Test_id`),
  CONSTRAINT `questions_ibfk_1` FOREIGN KEY (`Test_id`) REFERENCES `course` (`course_code`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `course` (
  `course_name` varchar(30) NOT NULL,
  `course_code` int NOT NULL,
  `subject` varchar(30) NOT NULL,
  `reference_material` varchar(50) NOT NULL,
  `Material_description` varchar(200) DEFAULT NULL,
  `quiz_code` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`course_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `answers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `test_id` int DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `question_id` int NOT NULL,
  `user_answer` char(1) NOT NULL,
  `is_correct` tinyint(1) NOT NULL,
  `timestamp` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `question_id` (`question_id`),
  KEY `answers_ibfk_2` (`test_id`),
  CONSTRAINT `answers_ibfk_1` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`),
  CONSTRAINT `answers_ibfk_2` FOREIGN KEY (`test_id`) REFERENCES `course` (`course_code`)
) ENGINE=InnoDB AUTO_INCREMENT=99 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO course(course_name,course_code,subject,reference_material,Material_description,quiz_code) VALUES ('Python Easy',1,'Python','https://youtu.be/kqtD5dpn9C8?si=buReA_VY_tUtuEwe','1-hour Python tutorial by Programming with Mosh on YouTube.','Quiz 1'),
 ('Python Advanced',2,'Python','https://youtu.be/rfscVS0vtbw?si=K5nAdqGsflt2dU6Q','4-hour Python tutorial by FreeCodeCamp on YouTube.','Quiz 2'),
 ('Java Easy',3,'Java','https://www.youtube.com/watch?v=A74TOX803D0','Java Programming for Beginners – Full Course','Quiz 1'),
 ('Java Advanced',4,'Java','https://www.youtube.com/watch?v=Ae-r8hsbPUo','Advanced Java Full Course 2023 | Advance Java Tutorial | J2EE, JSP, JDBC, Java API | Simplilearn','Quiz 2'),
 ('C++ Easy',5,'CPP','https://www.youtube.com/watch?v=NxS_0vR-PPg','C++ For Absolute Beginners | C++ Online Tutorial','Quiz 1'),
 ('C++ Advanced',6,'CPP','https://www.youtube.com/watch?v=8jLOx1hD3_o','C++ Programming Course - Beginner to Advanced','Quiz 2');


INSERT INTO  questions (id,question,choice_a,choice_b,choice_c,choice_d,correct_choice,question_id,Test_id) VALUES (1,'1) What is the correct way to create a variable with the numeric value 5 in Python?','A. num = int(5)','B. num = 5','C. int num = 5','D. 5 = num','B',1,1),
 (2,'2) Which of the following data types is NOT mutable in Python?','A. List','B. Dictionary','C. Tuple','D. Set','C',2,1),
 (3,'3) What is the output of the following code: print(type(\"Hello, World!\"))','A. <class \'string\'>','B. <class \'str\'>','C. <class \'text\'>','D. <class \'char\'>','B',3,1),
 (4,'4) Which of the following is a valid way to write a comment in Python?','A. // This is a comment','B. /* This is a comment */','C. # This is a comment','D. <!-- This is a comment -->','C',4,1),
 (5,'5) What does the following code print: print(10 // 3)','A. 3.33','B. 3.0','C. 3','D. 4','C',5,1),
 (6,'6) Which of the following is the correct syntax for a function in Python?','A. function myFunction():','B. def myFunction():','C. define myFunction():','D. func myFunction():','B',6,1),
 (7,'7) Which keyword is used to create a loop that repeats a block of code as long as a condition is true?','A. for','B. do','C. repeat','D. while','D',7,1),
 (8,'8) Which of the following operators is used for exponentiation in Python?','A. ^','B. **','C. exp','D. ^^','B',8,1),
 (9,'9) What will the following code output: print(\"Python\"[0])','A. P','B. y','C. o','D. n','A',9,1),
 (10,'10) What is the output of this code: x = [1, 2, 3] print(len(x))','A. 1','B. 2','C. 3','D. 4','C',10,1),
 (11,'1) What will be the output of the following code: print(\"5\" + \"6\")','A. 11','B. 56','C. 5 6','D. TypeError','B',1,2),
 (12,'2) Which function can convert a string to a float in Python?','A. int()','B. str()','C. float()','D. bool()','C',2,2),
 (13,'3) What is the result of this expression: 10 % 3?','A. 3','B. 1','C. 0','D. 10','B',3,2),
 (14,'4) In Python, which keyword is used to declare a lambda function?','A. def','B. lambda','C. func','D. return','B',4,2),
 (15,'5) Which of the following methods is used to add an item to the end of a list in Python?','A. append()','B. insert()','C. add()','D. extend()','A',5,2),
 (16,'6) What is the output of this code: print(list(range(2, 10, 2)))','A. [2, 4, 6, 8, 10]','B. [2, 4, 6, 8]','C. [2, 3, 4, 5, 6, 7, 8, 9]','D. [3, 5, 7, 9]','B',6,2),
 (17,'7) Which of the following methods removes the first occurrence of a specific element from a list?','A. pop()','B. remove()','C. del()','D. discard()','B',7,2),
 (18,'8) What will the following code output: print(\"Python\".lower())','A. python','B. PYTHON','C. Python','D. Error','A',8,2),
 (19,'9) How would you write a conditional statement that checks if a variable x is between 10 and 20?','A. if 10 < x < 20:','B. if x > 10 && x < 20:','C. if x > 10 and < 20:','D. if x is 10 and 20:','A',9,2),
 (20,'10) What will be the output of this code: x = \"Hello World\"; print(x[1:5])','A. Hell','B. ello','C. Hello','D. o W','B',10,2),
 (21,'1) Which of these is the correct syntax to output \"Hello World\" in Java?','A. System.out.println(\"Hello World\");','B. echo(\"Hello World\");','C. Console.WriteLine(\"Hello World\");','D. printf(\"Hello World\");','A',1,3),
 (22,'2) What is the correct file extension for Java files?','A. .java','B. .js','C. .jav','D. .jv','A',2,3),
 (23,'3) Which of the following is a valid keyword in Java?','A. void','B. Integer','C. string','D. boolean','A',3,3),
 (24,'4) What does JVM stand for?','A. Java Variable Machine','B. Java Virtual Module','C. Java Virtual Machine','D. Java Visible Method','C',4,3),
 (25,'5) Which data type is used to create a variable that should store text?','A. string','B. myString','C. String','D. Txt','C',5,3),
 (26,'6) Which method is used to find the length of a string in Java?','A. length()','B. getSize()','C. getLength()','D. size()','A',6,3),
 (27,'7) Which keyword is used to define a class in Java?','A. class','B. Class','C. define','D. new','A',7,3),
 (28,'8) Which of the following is the correct way to declare an integer variable in Java?','A. int x;','B. integer x;','C. num x;','D. x int;','A',8,3),
 (29,'9) Which of these is the default value of an int variable in Java?','A. 1','B. 0','C. null','D. -1','B',9,3),
 (30,'10) Which operator is used to compare two values in Java?','A. ==','B. =','C. equals','D. ><','A',10,3),
 (31,'1) What will be the output of the following code: System.out.println(10 + 20 + \"30\");','A. 30','B. 3030','C. 102030','D. 303030','B',1,4),
 (32,'2) Which of these is a reserved keyword in Java?','A. array','B. goto','C. main','D. input','B',2,4),
 (33,'3) Which method in Java is used to compare two strings for equality?','A. equals()','B. compare()','C. ==','D. isEqual()','A',3,4),
 (34,'4) What is the output of this code: System.out.println(\"Hello\".charAt(1));','A. H','B. e','C. l','D. o','B',4,4),
 (35,'5) In Java, which access modifier makes a variable accessible within all classes in the same package?','A. public','B. private','C. protected','D. default','D',5,4),
 (36,'6) Which of these statements will successfully convert a string \"123\" to an integer?','A. Integer.parseInt(\"123\")','B. Integer.valueOf(\"123\")','C. Integer.toInt(\"123\")','D. toInt(\"123\")','A',6,4),
 (37,'7) What will be the output of this code: System.out.println(3 * 3 + 5 / 5);','A. 9','B. 10','C. 8','D. 11','B',7,4),
 (38,'8) What is the correct way to create an array in Java?','A. int arr[] = new int[5];','B. int arr = new int[5];','C. int[] arr = int[5];','D. int arr[5];','A',8,4),
 (39,'9) What is the default value of a boolean variable in Java?','A. true','B. false','C. null','D. 0','B',9,4),
 (40,'10) What will be the output of the following code: System.out.println(\"Java\".substring(1, 3));','A. Ja','B. av','C. aJ','D. Java','B',10,4),
 (41,'1) Which of these is the correct way to declare a variable in C++?','A. int x;','B. int:x;','C. x int;','D. x:int;','A',1,5),
 (42,'2) What is the output of cout << \"Hello World\"; in C++?','A. Hello World','B. Hello','C. World','D. \"Hello World\"','A',2,5),
 (43,'3) Which of the following is a valid way to create a comment in C++?','A. // This is a comment','B. # This is a comment','C. /* This is a comment','D. <!-- This is a comment -->','A',3,5),
 (44,'4) What is the correct syntax to output \"Hello World\" in C++?','A. cout << \"Hello World\";','B. print(\"Hello World\");','C. echo \"Hello World\";','D. Console.WriteLine(\"Hello World\");','A',4,5),
 (45,'5) Which operator is used to access members of a structure?','A. .','B. ->','C. &','D. :','A',5,5),
 (46,'6) Which of the following is a standard library in C++?','A. iostream','B. stdio.h','C. math.h','D. string.h','A',6,5),
 (47,'7) What is the default value of a global variable in C++?','A. 0','B. random value','C. undefined','D. NULL','A',7,5),
 (48,'8) Which of these is the correct way to declare an array in C++?','A. int arr[10];','B. int arr();','C. arr[10] int;','D. int[10] arr;','A',8,5),
 (49,'9) What will be the output of cout << 10 + 20;?','A. 10','B. 20','C. 30','D. 1020','C',9,5),
 (50,'10) Which keyword is used to create a class in C++?','A. class','B. struct','C. object','D. new','A',10,5),
 (51,'1) What will be the output of the following code: cout << 5 + 2 * 3;?','A. 21','B. 11','C. 16','D. 10','B',1,6),
 (52,'2) Which of these is not a valid C++ data type?','A. int','B. char','C. string','D. text','D',2,6),
 (53,'3) Which function is used to find the length of a string in C++?','A. length()','B. size()','C. strlen()','D. getLength()','C',3,6),
 (54,'4) What is the output of the following code: int x = 5; cout << ++x;?','A. 4','B. 5','C. 6','D. 7','C',4,6),
 (55,'5) Which operator is used for pointer dereferencing in C++?','A. *','B. &','C. ->','D. #','A',5,6),
 (56,'6) In C++, which keyword is used to define a function?','A. define','B. void','C. func','D. return','B',6,6),
 (57,'7) Which of the following is the correct way to allocate dynamic memory for an integer in C++?','A. int* p = new int;','B. int p = new int;','C. int* p = malloc(sizeof(int));','D. p = int*;','A',7,6),
 (58,'8) What is the output of cout << (10 > 5 ? \"Yes\" : \"No\");?','A. Yes','B. No','C. 10 > 5','D. 10 < 5','A',8,6),
 (59,'9) What does the virtual keyword indicate in C++?','A. It indicates that a function can be overridden in a derived class.','B. It indicates that a function cannot be overridden.','C. It indicates that a function is static.','D. It indicates that a function is private.','A',9,6),
 (60,'10) Which of these is the correct syntax for creating a constructor in C++?','A. ClassName();','B. ClassName{};','C. void ClassName();','D. constructor ClassName();','A',10,6);
